version: '3'
services:
    db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_DEFAULT_USER}
            MYSQL_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
        volumes:
            - ./log/mysql:/var/log/mysql
            - db_data:/var/lib/mysql
        networks:
            - vnet
        ports:
            - ${DB_SERVER_PORT}:3306
        restart: unless-stopped
    web:
        container_name: nodejs
        build:
            context: .
            dockerfile: docker/nodejs/Dockerfile
            target: devstage
            # args:
                # uid: ${UID}
        volumes: 
            - ./source:/home/node/app
        networks:
            - vnet
        ports:
            - ${BACKEND_SERVER_PORT}:3333
        depends_on: 
            - db
        links:
            - db
        restart: unless-stopped
volumes:
    db_data:
networks:
  vnet:
    driver: bridge